import { createFileRoute } from "@tanstack/react-router";
import { Clock, MapPin, Menu, Phone, Quote, Star } from "lucide-react";
import { Button } from "../components/Button";
import photo0 from "../assets/restaurant-0.jpg.asset.json";
import photo1 from "../assets/restaurant-1.jpg.asset.json";
import photo2 from "../assets/restaurant-2.jpg.asset.json";
import photo5 from "../assets/restaurant-5.jpg.asset.json";

const mapUrl = "https://maps.google.com/?cid=17582143241383883018";
const phoneUrl = "tel:+9779841451986";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Tibetan and Nepali Kitchen | Kathmandu" },
      { name: "description", content: "Authentic Tibetan and Nepali food in Kathmandu. Momos, thukpa and thali, open daily 9 AM–11 PM." },
      { property: "og:title", content: "Tibetan and Nepali Kitchen, Kathmandu" },
      { property: "og:description", content: "Honest Himalayan flavours, handmade with heart in Kathmandu." },
      { property: "og:image", content: photo0.url },
    ],
  }),
  component: Index,
});

const menuSections = [
  { title: "From the steamer", image: photo0.url, dishes: [["Buff Momo", "Hand-folded dumplings with tomato-sesame achar"], ["Chicken Momo", "Juicy chicken, Himalayan spices and fiery chilli paste"], ["Vegetable Momo", "Seasonal vegetables, herbs and warming spices"]] },
  { title: "From the hearth", image: photo1.url, dishes: [["Mutton Thali", "Goat curry, lentils, rice, vegetables, pickle and greens"], ["Chicken Thukpa", "Nourishing Tibetan noodle soup with vegetables"], ["Veg Thakali Set", "Traditional dal bhat with seasonal accompaniments"]] },
  { title: "Sweet & warming", image: photo2.url, dishes: [["Himalayan Milk Tea", "Fragrant spiced tea, simmered with milk"], ["Lassi", "Cool, creamy and freshly blended"], ["Seasonal Sweet", "Ask our team for today’s Nepali dessert"]] },
];

function Index() {
  return (
    <main className="overflow-hidden bg-background text-foreground">
      <header className="absolute inset-x-0 top-0 z-20 border-b border-primary-foreground/15"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-10"><a href="#top" className="font-display text-lg font-bold leading-none text-primary-foreground">Tibetan <span className="text-accent">&</span> Nepali<br/><span className="text-xs font-sans font-medium uppercase tracking-[0.3em]">Kitchen</span></a><nav className="hidden gap-8 text-xs font-bold uppercase tracking-[0.16em] text-primary-foreground md:flex"><a href="#menu">Menu</a><a href="#story">Our story</a><a href="#visit">Visit</a></nav><Button href={phoneUrl} className="hidden sm:inline-flex">Reserve a table</Button><a href="#menu" className="text-primary-foreground sm:hidden" aria-label="View menu"><Menu /></a></div></header>
      <section id="top" className="relative flex min-h-[760px] items-end md:min-h-[840px] md:items-center"><img src={photo1.url} alt="A generous spread of Tibetan and Nepali dishes" className="absolute inset-0 h-full w-full object-cover"/><div className="hero-shade absolute inset-0"/><div className="relative mx-auto w-full max-w-7xl px-5 pb-20 pt-36 lg:px-10"><div className="reveal max-w-3xl"><p className="mb-5 flex items-center gap-3 text-xs font-bold uppercase tracking-[0.28em] text-accent"><span className="h-px w-10 bg-accent"/> From the Himalayas to your table</p><h1 className="text-6xl font-semibold leading-[0.9] tracking-[-0.03em] text-primary-foreground sm:text-7xl md:text-8xl lg:text-9xl">Honest food.<br/><em className="font-medium text-accent">Warm hearts.</em></h1><p className="mt-7 max-w-xl text-base leading-8 text-primary-foreground/80 md:text-lg">Discover the soulful flavours of Nepal and Tibet—hand-folded momos, comforting thukpa, and generous thali made just as they should be.</p><div className="mt-9 flex flex-wrap gap-4"><Button href={phoneUrl}>Reserve your table</Button><Button href="#menu" variant="outline" className="border-primary-foreground/40 text-primary-foreground">Explore the menu</Button></div><div className="mt-10 flex items-center gap-3 text-primary-foreground"><div className="flex text-accent">{[1,2,3,4,5].map(n=><Star key={n} className="h-4 w-4 fill-current"/>)}</div><strong>4.7</strong><span className="text-sm text-primary-foreground/65">from 257 Google reviews</span></div></div></div></section>
      <section id="menu" className="px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-8 border-b border-border pb-12 md:grid-cols-[1fr_1.3fr] md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-primary">A taste of home</p><h2 className="mt-3 text-5xl font-semibold md:text-7xl">The menu</h2></div><p className="max-w-2xl leading-7 text-muted-foreground">Bold Himalayan spices, satisfying portions and recipes rooted in tradition. Prices and daily availability are confirmed at the restaurant.</p></div><div className="mt-12 grid gap-8 lg:grid-cols-3">{menuSections.map((section,index)=><article key={section.title} className="group"><div className="relative h-80 overflow-hidden"><img src={section.image} alt={`${section.title} dishes`} loading={index ? "lazy" : "eager"} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="image-shade absolute inset-0"/><p className="absolute bottom-5 left-5 text-xs font-bold uppercase tracking-[0.2em] text-primary-foreground">0{index+1}</p></div><h3 className="mt-7 text-3xl font-semibold">{section.title}</h3><div className="mt-5 divide-y divide-border">{section.dishes.map(([name,desc])=><div key={name} className="py-5"><h4 className="font-sans text-sm font-bold uppercase tracking-[0.1em]">{name}</h4><p className="mt-2 text-sm leading-6 text-muted-foreground">{desc}</p></div>)}</div></article>)}</div></div></section>
      <section id="story" className="bg-secondary text-secondary-foreground"><div className="mx-auto grid max-w-7xl lg:grid-cols-2"><div className="relative min-h-[540px]"><img src={photo5.url} alt="Authentic dishes served at Tibetan and Nepali Kitchen" loading="lazy" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute -bottom-7 right-7 bg-primary px-6 py-5 text-primary-foreground"><strong className="font-display text-4xl">4.7</strong><span className="ml-2 text-xs uppercase tracking-widest">Guest rating</span></div></div><div className="flex items-center px-6 py-24 lg:px-20"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-accent">Our story</p><h2 className="mt-4 text-5xl font-semibold leading-none md:text-7xl">Food that feels<br/><em className="text-accent">like home.</em></h2><p className="mt-8 max-w-xl leading-8 text-secondary-foreground/75">Tucked into the heart of Kathmandu, Tibetan and Nepali Kitchen is a neighbourhood table built around genuine hospitality. Guests come for authentic, nourishing food and return for the friendly team, remarkable value and unforgettable flavours.</p><p className="mt-5 max-w-xl leading-8 text-secondary-foreground/75">From steaming momos to the much-loved mutton thali, everything is served without fuss—just generous, honest cooking.</p></div></div></div></section>
      <section className="px-5 py-24 text-center lg:py-32"><Quote className="mx-auto h-10 w-10 text-primary"/><blockquote className="mx-auto mt-8 max-w-4xl font-display text-3xl font-medium leading-tight md:text-5xl">“Amazing Nepali food—full of flavor and truly authentic. The service is very friendly, attentive, and professional.”</blockquote><p className="mt-7 text-xs font-bold uppercase tracking-[0.2em] text-primary">Paweł Wróblewski · Google review</p></section>
      <section id="visit" className="grid bg-card lg:grid-cols-2"><iframe title="Map to Tibetan and Nepali Kitchen" loading="lazy" className="min-h-[480px] w-full" src="https://www.google.com/maps?q=27.7147318,85.3101005&z=17&output=embed"/><div className="px-6 py-20 md:px-16 lg:px-20 lg:py-24"><p className="text-xs font-bold uppercase tracking-[0.25em] text-primary">Come share our table</p><h2 className="mt-4 text-5xl font-semibold md:text-7xl">Visit us</h2><div className="mt-10 space-y-8 border-y border-border py-9"><div className="flex gap-5"><MapPin className="mt-1 text-primary"/><div><strong>In the heart of Kathmandu</strong><p className="mt-1 text-sm text-muted-foreground">P876+V2X, Kathmandu 44600, Nepal</p></div></div><div className="flex gap-5"><Clock className="mt-1 text-primary"/><div><strong>Open every day</strong><p className="mt-1 text-sm text-muted-foreground">9:00 AM – 11:00 PM</p></div></div><div className="flex gap-5"><Phone className="mt-1 text-primary"/><div><strong>Call for a table</strong><p className="mt-1 text-sm text-muted-foreground">+977 984-1451986</p></div></div></div><div className="mt-9 flex flex-wrap gap-4"><Button href={mapUrl} target="_blank" rel="noreferrer">Get directions</Button><Button href={phoneUrl} variant="outline">Call restaurant</Button></div></div></section>
      <footer className="bg-secondary px-5 py-12 text-secondary-foreground lg:px-10"><div className="mx-auto flex max-w-7xl flex-col gap-6 text-center md:flex-row md:items-end md:justify-between md:text-left"><div><p className="font-display text-2xl font-bold">Tibetan <span className="text-accent">&</span> Nepali Kitchen</p><p className="mt-2 text-xs uppercase tracking-[0.18em] text-secondary-foreground/55">Authentic Himalayan kitchen · Kathmandu</p></div><a href={mapUrl} target="_blank" rel="noreferrer" className="text-xs font-bold uppercase tracking-widest hover:text-accent">Google reviews</a><p className="text-xs text-secondary-foreground/45">© 2026 Tibetan and Nepali Kitchen</p></div></footer>
    </main>
  );
}
